FROM golang:1.25-alpine AS builder
WORKDIR /src
COPY ./vendor ./vendor
COPY ./go.mod ./go.mod
COPY ./go.sum ./go.sum
COPY ./cmd/receiver/ ./receiver
RUN CGO_ENABLED=0 GOOS=linux \
    go build -o receiver ./receiver


FROM alpine
WORKDIR /app
COPY --from=builder ./src/receiver ./
ENV PATH=$PATH:/app
CMD ./receiver

